name:                warpt3
version:             0.1.0.0
github:              "githubuser/warpt3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md


default-extensions: OverloadedStrings, DeriveGeneric
#DeriveAnyClass

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/warpt3#readme>

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- bytestring
- http-types
- aeson
- text
- mtl
- time
- unordered-containers
- exceptions
- random
- postgresql-simple
- postgresql-simple-migration
- file-embed
- regex-pcre
- configurator


library:
  source-dirs: src
 
executables:
  warpt3:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - warpt3
    

tests:
  warpt3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warpt3
    - hspec
